eureka:
  client:
    serviceUrl:
      defaultZone : http://localhost:9092/eureka
spring:
  cloud:
    gateway:
      routes:
        -id: microservice-projet
        uri: lb://microservice-projet
        predicates : 
          -Path=/projet/**
          filtres:
            -RewritePath=/projet/(?<path>.*), /$\{path
            -id: microservice-utilisateur
        uri: lb://microservice-utilisateur
        predicates : 
          -Path=/utilisateur/**
          filtres:
            -RewritePath=/utilisateur/(?<path>.*), /$\{path}
        
  

